# Generated by Django 3.2.3 on 2021-07-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'verbose_name_plural': 'Tipo Gastos'},
        ),
    ]
