# Generated by Django 3.2.3 on 2021-08-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Clientes', '0001_initial'),
        ('app_Gastos', '0002_auto_20210720_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogasto',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Clientes.cliente', verbose_name='Cliente'),
        ),
    ]
