# Generated by Django 3.2.3 on 2021-07-15 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('Apellido', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='FuenteDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Registroc', models.DateField()),
                ('Fuente', models.CharField(max_length=25)),
                ('Saldo', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Fuente de Dinero',
                'verbose_name_plural': 'Fuente de Dinero',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'TipoGasto',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Registro', models.DateField()),
                ('Monto', models.IntegerField()),
                ('Fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.fuentedinero', verbose_name='Fuente')),
            ],
            options={
                'verbose_name_plural': 'Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Registro', models.DateField()),
                ('Monto', models.IntegerField()),
                ('Fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.fuentedinero', verbose_name='Fuente')),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipogasto', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Gasto',
            },
        ),
    ]
