# Generated by Django 3.2.3 on 2021-08-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name_plural': 'Ingresos'},
        ),
    ]
