# Generated by Django 3.2.3 on 2021-07-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Registroc', models.DateField()),
                ('Fuente', models.CharField(max_length=25)),
                ('Saldo', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Fuente de Dinero',
                'verbose_name_plural': 'Fuente de Dinero',
            },
        ),
    ]
