# Generated by Django 3.2.3 on 2021-07-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Fuente_Dinero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuentedinero',
            old_name='Fecha_Registroc',
            new_name='Fecha_Registro',
        ),
    ]
